/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC721TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721TokenReceiver__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC20Partial",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Partial__factory>;
    getContractFactory(
      name: "IERC721Partial",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Partial__factory>;
    getContractFactory(
      name: "IRoyaltyEngineV1Partial",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRoyaltyEngineV1Partial__factory>;
    getContractFactory(
      name: "Nix",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Nix__factory>;
    getContractFactory(
      name: "NixHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NixHelper__factory>;
    getContractFactory(
      name: "Owned",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Owned__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;

    getContractAt(
      name: "ERC721TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721TokenReceiver>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC20Partial",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Partial>;
    getContractAt(
      name: "IERC721Partial",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Partial>;
    getContractAt(
      name: "IRoyaltyEngineV1Partial",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IRoyaltyEngineV1Partial>;
    getContractAt(
      name: "Nix",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Nix>;
    getContractAt(
      name: "NixHelper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NixHelper>;
    getContractAt(
      name: "Owned",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Owned>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
